"use client";
import { LazyMotion, MotionConfig, domAnimation, m, useMotionValueEvent, useReducedMotion, useScroll, useTransform } from "motion/react";
import { useEffect, useRef, useState } from "react";
import { Menu, X } from "lucide-react";
import { cn } from "@/lib/utils";
const ease=[0.22,1,0.36,1] as const;
export function LandingMotionProvider({children}:{children:React.ReactNode}){return <LazyMotion features={domAnimation} strict><MotionConfig reducedMotion="user" transition={{duration:.7,ease}}>{children}</MotionConfig></LazyMotion>}
export function ScrollNavbar({children}:{children:React.ReactNode}){const{scrollY}=useScroll();const[scrolled,setScrolled]=useState(false);const ref=useRef(false);useMotionValueEvent(scrollY,"change",latest=>{const next=latest>28;if(next!==ref.current){ref.current=next;setScrolled(next)}});return <m.header data-scrolled={scrolled} initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} transition={{duration:.55,ease}} className="landing-navbar fixed inset-x-0 top-0 z-50">{children}</m.header>}
const navItems=[{id:"recursos",label:"Recursos"},{id:"como-funciona",label:"Como funciona"},{id:"life-score",label:"Life Score"},{id:"finbot",label:"FinBot"},{id:"planos",label:"Planos"},{id:"faq",label:"FAQ"}];
export function LandingNav(){const[active,setActive]=useState<string|null>(null);const[open,setOpen]=useState(false);useEffect(()=>{const elements=navItems.map(({id})=>document.getElementById(id)).filter((element):element is HTMLElement=>Boolean(element));const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActive(visible.target.id)},{rootMargin:"-25% 0px -55%",threshold:[.08,.25,.5]});elements.forEach(element=>observer.observe(element));return()=>observer.disconnect()},[]);return <><nav className="hidden items-center gap-5 text-xs text-zinc-600 lg:flex dark:text-zinc-400" aria-label="Seções da página">{navItems.map(({id,label})=><a key={id} href={`#${id}`} data-active={active===id} className="landing-nav-link hover:text-zinc-950 dark:hover:text-white">{label}{active===id&&<m.span layoutId="landing-active-section" className="absolute inset-x-0 bottom-0 h-px bg-gold-400" transition={{type:"spring",stiffness:420,damping:34}}/>}</a>)}</nav><button onClick={()=>setOpen(value=>!value)} className="ml-auto grid size-10 place-items-center rounded-xl border border-zinc-200 bg-white/70 lg:hidden dark:border-white/10 dark:bg-zinc-900/70" aria-label={open?"Fechar menu":"Abrir menu"} aria-expanded={open}>{open?<X className="size-5"/>:<Menu className="size-5"/>}</button>{open&&<div className="absolute left-4 right-4 top-[calc(100%+8px)] rounded-2xl border border-zinc-200 bg-white/95 p-2 shadow-2xl backdrop-blur-xl lg:hidden dark:border-white/10 dark:bg-zinc-950/95">{navItems.map(({id,label})=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)} className="block rounded-xl px-4 py-3 text-sm font-medium text-zinc-600 hover:bg-zinc-100 dark:text-zinc-300 dark:hover:bg-white/[.06]">{label}</a>)}<div className="mt-1 grid grid-cols-2 gap-2 border-t border-zinc-100 p-2 pt-3 dark:border-white/10"><a href="/auth/login" className="rounded-xl border border-zinc-200 px-3 py-2.5 text-center text-xs font-semibold dark:border-white/10">Entrar</a><a href="/auth/signup" className="rounded-xl bg-gold-400 px-3 py-2.5 text-center text-xs font-bold text-black">Começar grátis</a></div></div>}</>}
export function HeroItem({children,index,className}:{children:React.ReactNode;index:number;className?:string}){const reduced=useReducedMotion();return <m.div initial={{opacity:0,y:reduced?0:22,scale:reduced?1:.985}} animate={{opacity:1,y:0,scale:1}} transition={{duration:.72,delay:.1+index*.09,ease}} className={className}>{children}</m.div>}
export function Reveal({children,className,delay=0,distance=28}:{children:React.ReactNode;className?:string;delay?:number;distance?:number}){const reduced=useReducedMotion();return <m.div initial={{opacity:0,y:reduced?0:distance,scale:reduced?1:.992}} whileInView={{opacity:1,y:0,scale:1}} viewport={{once:true,amount:.16,margin:"0px 0px -60px"}} transition={{duration:.68,delay,ease}} className={className}>{children}</m.div>}
export function FloatingPreview({children}:{children:React.ReactNode}){const ref=useRef<HTMLDivElement>(null);const reduced=useReducedMotion();const{scrollYProgress}=useScroll({target:ref,offset:["start end","end start"]});const y=useTransform(scrollYProgress,[0,.5,1],[34,0,-24]);const scale=useTransform(scrollYProgress,[0,.5,1],[.975,1,.992]);const shadow=useTransform(scrollYProgress,[0,.5,1],["0 28px 70px rgba(0,0,0,.15)","0 55px 130px rgba(0,0,0,.24)","0 32px 80px rgba(0,0,0,.17)"]);return <m.div ref={ref} initial={{opacity:0,y:reduced?0:40,scale:reduced?1:.97}} whileInView={{opacity:1,y:0,scale:1}} viewport={{once:true,amount:.12}} transition={{duration:.9,delay:.18,ease}} style={reduced?undefined:{y,scale,boxShadow:shadow}} className="will-change-transform">{children}</m.div>}
const particles=[[8,22,0,15],[17,72,-4,19],[28,39,-8,17],[42,82,-3,21],[55,16,-11,18],[66,61,-6,23],[76,31,-13,20],[88,74,-9,16]] as const;
export function AmbientBackground(){return <div className="landing-ambient pointer-events-none absolute inset-0 overflow-hidden" aria-hidden="true"><div className="landing-grid absolute inset-0"/><div className="landing-orb landing-orb-one"/><div className="landing-orb landing-orb-two"/>{particles.map(([left,top,delay,duration],index)=><i key={index} className={cn("landing-particle",index%3===0&&"landing-particle-lg")} style={{left:`${left}%`,top:`${top}%`,animationDelay:`${delay}s`,animationDuration:`${duration}s`}}/>)}</div>}
