"use client";
import { useState } from "react";
import { Plus } from "lucide-react";
import { useLifeData } from "@/hooks/useLifeData";
import { MealCard, MealUploadBox } from "@/components/nutrition/nutrition-widgets";
import { PageHeader } from "@/components/life/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "@/hooks/useToast";
export default function MealsPage(){const d=useLifeData();const[show,setShow]=useState(false);const[name,setName]=useState("");const[cal,setCal]=useState("450");function add(){if(!name.trim())return;d.addMeal({name:name.trim(),calories:Number(cal)||0,proteins:25,carbs:45,fats:15,mealTime:new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}),notes:"Registro manual"});setName("");setShow(false);toast({title:"Refeição registrada",description:"Seu resumo nutricional foi atualizado.",variant:"success"})}return <div className="space-y-7"><PageHeader eyebrow="Alimentação · Refeições" title="Seu diário alimentar." description="Registre o que comeu com rapidez. Os dados ficam prontos para uma futura análise inteligente." action={<Button onClick={()=>setShow(v=>!v)} className="rounded-xl bg-gold-400 text-black"><Plus className="mr-2 size-4"/>Nova refeição</Button>}/>{show&&<div className="life-card grid gap-4 rounded-2xl p-5 lg:grid-cols-[1fr_.7fr]"><div className="space-y-3"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da refeição" className="h-11 rounded-xl" autoFocus/><div className="grid grid-cols-2 gap-3"><Input value={cal} onChange={e=>setCal(e.target.value)} type="number" placeholder="Calorias"/><Input value="25" readOnly aria-label="Proteínas estimadas"/></div><textarea className="min-h-24 w-full rounded-xl border bg-transparent p-3 text-sm outline-none focus:border-gold-400" placeholder="Observações"/><Button onClick={add} className="w-full rounded-xl bg-zinc-950 text-white dark:bg-gold-400 dark:text-black">Salvar refeição</Button></div><MealUploadBox/></div>}<div className="grid gap-3">{d.meals.map(m=><MealCard key={m.id} meal={m} onDelete={()=>{d.deleteMeal(m.id);toast({title:"Refeição removida"})}}/>)}</div></div>}
