"use client";
import { useEffect, useState } from "react";
import { Clock3, Pause, Play, RotateCcw } from "lucide-react";

export function WeeklyProgress({ value }: { value: number }) { return <div className="life-card rounded-2xl p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Progresso semanal</p><p className="mt-1 text-[11px] text-zinc-500">Consistência nos últimos 7 dias</p></div><strong className="font-display text-2xl text-gold-500">{value}%</strong></div><div className="mt-6 flex items-end justify-between gap-2">{[68,85,55,92,78,45,value].map((height,i)=><div className="flex flex-1 flex-col items-center gap-2" key={i}><div className="flex h-24 w-full items-end rounded-full bg-zinc-100 dark:bg-white/[.05]"><i className="w-full rounded-full bg-gradient-to-t from-gold-500 to-gold-300 transition-all" style={{height:`${height}%`}} /></div><span className="text-[9px] text-zinc-400">{["S","T","Q","Q","S","S","D"][i]}</span></div>)}</div></div> }

export function TimeTrackerCard() { const [seconds,setSeconds]=useState(0); const [running,setRunning]=useState(false); useEffect(()=>{if(!running)return; const id=setInterval(()=>setSeconds(s=>s+1),1000); return()=>clearInterval(id)},[running]); const formatted = new Date(seconds*1000).toISOString().slice(11,19); return <div className="overflow-hidden rounded-2xl bg-zinc-950 p-5 text-white dark:border dark:border-white/10"><div className="flex items-center gap-2 text-xs font-semibold text-gold-300"><Clock3 className="size-4" />Foco agora</div><p className="mt-5 font-display text-4xl font-semibold tabular-nums tracking-tight">{formatted}</p><p className="mt-1 text-xs text-zinc-400">Projeto pessoal</p><div className="mt-5 flex gap-2"><button onClick={()=>setRunning(v=>!v)} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-gold-400 px-3 py-2.5 text-xs font-bold text-black">{running?<Pause className="size-4"/>:<Play className="size-4"/>}{running?"Pausar":"Começar"}</button><button onClick={()=>{setRunning(false);setSeconds(0)}} className="grid size-10 place-items-center rounded-xl bg-white/10 text-zinc-300"><RotateCcw className="size-4"/></button></div></div> }

export function RoutineCalendar() { const today=new Date().getDate(); return <div className="life-card rounded-2xl p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Calendário</p><p className="mt-1 text-[11px] text-zinc-500">{new Date().toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</p></div></div><div className="mt-5 grid grid-cols-7 gap-1 text-center">{["D","S","T","Q","Q","S","S"].map((d,i)=><span key={i} className="pb-2 text-[9px] font-bold text-zinc-400">{d}</span>)}{Array.from({length:35},(_,i)=>i+1).map(day=><span key={day} className={`grid aspect-square place-items-center rounded-lg text-[11px] ${day===today?"bg-gold-400 font-bold text-black":day%4===0?"bg-gold-400/10 text-gold-500":"text-zinc-500"}`}>{day<=30?day:""}</span>)}</div></div> }
