import Link from "next/link";
import { ArrowLeft, BadgeCheck, Sparkles } from "lucide-react";

export function AuthShell({ children, title, description }: { children: React.ReactNode; title: string; description: string }) {
  return <main className="grid min-h-screen bg-[#fafaf8] lg:grid-cols-[1fr_1.05fr] dark:bg-[#090909]">
    <section className="flex items-center justify-center px-5 py-20 sm:px-10"><div className="w-full max-w-md"><Link href="/" className="mb-10 inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-zinc-950 dark:hover:text-white"><ArrowLeft className="size-4" /> Voltar ao início</Link><div className="mb-8"><Link href="/" className="flex items-center gap-2.5 font-display text-xl font-bold"><span className="grid size-10 place-items-center rounded-xl bg-zinc-950 text-gold-300 dark:bg-gold-400 dark:text-black"><Sparkles className="size-4" /></span>FinMb</Link><h1 className="mt-8 font-display text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h1><p className="mt-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">{description}</p></div>{children}</div></section>
    <aside className="relative hidden overflow-hidden bg-zinc-950 p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_15%,rgba(212,175,55,.22),transparent_38%)]" /><div className="grid-fade absolute inset-0 opacity-20" /><span className="relative text-xs font-semibold tracking-[.2em] text-gold-300">FINANÇAS COM CLAREZA</span><div className="relative max-w-xl"><blockquote className="font-display text-4xl font-medium leading-tight">“Organização financeira não deveria parecer um segundo emprego.”</blockquote><div className="mt-10 space-y-4">{["Seus dados protegidos por RLS", "Decisões guiadas por contexto", "Uma interface feita para respirar"].map(item => <div className="flex items-center gap-3 text-sm text-zinc-300" key={item}><BadgeCheck className="size-5 text-gold-300" />{item}</div>)}</div></div><p className="relative text-xs text-zinc-600">FinMb · Seu dinheiro, em perspectiva.</p></aside>
  </main>;
}
